package breakers.code.grammar.tokens;

public enum TYPES {

    COMPARASION_OPERATOR,
    OPERATOR,
    PARENTHESIS,
    PONCTUATION,
    VARIABLE_NAME,
    VECTOR_NAME,
    FUNCTION_NAME,
    CONSTANT_NAME,
    BASIC_TYPE,
    GENERAL,
    IO_FUNCTION,
    INTERNAL_FUNCTIONS,
    INFORMATION_FLOW,
    SEMICOLON,

    VARIABLE,
    CONSTANT,
    NUMERIC,
    STRING,
    FUNCTION,
    BOOLEAN;

}
